# Generated by Django 2.2 on 2019-05-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(default='media/no-img.jpg', upload_to='media')),
                ('content', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
            ],
        ),
    ]
